### ISSUE TITLE
how to use pip in venv

### ISSUE THREAD

**Issue by Gldkslfmsd** [JSALT2024/demo#1]
Dominik documents this (for himself)

when activating venv, instead of `pip install $x` do `python3 -m pip install $x`

(Jirka told me this, I haven't tried.)

**Comment by VaJavorek** [comment]
Why is this in issues?

**Comment by Gldkslfmsd** [comment]
because it should be in the .md documentation but we are too lazy to put it there. This is a good compromise. It's accessible to others as well

**Comment by VaJavorek** [comment]
As correctly stated in the doc, use `.venv/bin/pip3 install $x`
https://github.com/JSALT2024/demo/blob/master/docs/development-rockfish.md#creating-python-venv

**Comment by Gldkslfmsd** [comment]
but it didn't work to me

**Comment by Gldkslfmsd** [comment]
Jirka knows. We keep this issue until it gets a priority

**Comment by Jirka-Mayer** [comment]
Fixed in c8b642b4260d4b4cde82a7179f7d385f7751af4b
